arm:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  mode: local
  stop_optimization_on_valid_solution: true
  position_scale: 1.0
  rotation_scale: 0.1
  position_threshold: 0.001
  orientation_threshold: 0.5
  cost_threshold: 0.001
  minimal_displacement_weight: 0.01
  gd_step_size: 0.0001
  